# Generated by Django 5.2.6 on 2025-09-05 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Короткое название')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Не удалось')], max_length=10)),
                ('total_records', models.IntegerField()),
                ('added', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('errors', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=50, verbose_name='Инициалы')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('internal_phone', models.CharField(max_length=20, verbose_name='Внутренний телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('hierarchy', models.IntegerField(choices=[(1, 'Высшее руководство (ГД)'), (2, 'Первые заместители'), (3, 'Заместители'), (4, 'Руководители центров'), (5, 'Руководители управлений'), (6, 'Руководители отделов'), (7, 'Специалисты'), (8, 'Ассистенты')], default=7, verbose_name='Уровень иерархии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['department__level', 'department__name', 'hierarchy', 'full_name'],
                'unique_together': {('full_name', 'internal_phone')},
            },
        ),
    ]
