# Generated by Django 5.2.6 on 2025-09-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабинет'),
        ),
    ]
